### ISSUE TITLE
Unused graphql dependency

### ISSUE THREAD

**Issue by DavidShaw337** [stevecaldwell77/graphql-request-appsync-iam-js#2]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Could the "graphql" dependency be removed? It doesn't seem to do anything, and there's a check in that package that breaks it if it finds any other versions of itself. I have another dependency that uses graphql "^14.7.0", and it won't work as long as this is installed.

**Comment by stevecaldwell77** [comment]
`graphql-request` requires `graphql` to be installed - https://github.com/prisma-labs/graphql-request#faq

However, I think if I refactor this package to make `graphql` a peer dependency with a wide range, it should solve your problem. I'm on vacation at the moment, but will try that out soon.

**Comment by DavidShaw337** [comment]
I don't know how I missed that `graphql-request` has `graphql` as a peerDependency. Sorry about that.

But I think you're right, making `graphql` a peerDependency of this package should fix my problem. It looks like the current version of `graphql-request` allows versions "14 - 16". If you match that, then everything should still work.

**Comment by stevecaldwell77** [comment]
Fixed in version `2.1.1`
